export const PIXABAY_CATEGORIES = [
  { id: "backgrounds", label: "Backgrounds" },
  { id: "fashion", label: "Fashion" },
  { id: "nature", label: "Nature" },
  { id: "science", label: "Science" },
  { id: "education", label: "Education" },
  { id: "feelings", label: "Feelings" },
  { id: "health", label: "Health" },
  { id: "people", label: "People" },
  { id: "religion", label: "Religion" },
  { id: "places", label: "Places" },
  { id: "animals", label: "Animals" },
  { id: "industry", label: "Industry" },
  { id: "computer", label: "Computer" },
  { id: "food", label: "Food" },
  { id: "sports", label: "Sports" },
  { id: "transportation", label: "Transportation" },
  { id: "travel", label: "Travel" },
  { id: "buildings", label: "Buildings" },
  { id: "business", label: "Business" },
  { id: "music", label: "Music" },
] as const;
